---
title: "B3"
format: html
editor: visual
---

```{r}
library(RCurl)
library(utils)
```


```{r}
# download status invest
status_invest <- "https://statusinvest.com.br/category/advancedsearchresultexport?search=%7B%22Sector%22%3A%22%22%2C%22SubSector%22%3A%22%22%2C%22Segment%22%3A%22%22%2C%22my_range%22%3A%220%3B25%22%2C%22dy%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22p_L%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22peg_Ratio%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22p_VP%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22p_Ativo%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22margemBruta%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22margemEbit%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22margemLiquida%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22p_Ebit%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22eV_Ebit%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22dividaLiquidaEbit%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22dividaliquidaPatrimonioLiquido%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22p_SR%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22p_CapitalGiro%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22p_AtivoCirculante%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22roe%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22roic%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22roa%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22liquidezCorrente%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22pl_Ativo%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22passivo_Ativo%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22giroAtivos%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22receitas_Cagr5%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22lucros_Cagr5%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22liquidezMediaDiaria%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22vpa%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22lpa%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%2C%22valorMercado%22%3A%7B%22Item1%22%3Anull%2C%22Item2%22%3Anull%7D%7D&CategoryType=1"

download.file(status_invest, destfile = "data.csv")

dataset <- readr::read_csv2("data.csv")
```

# Bazin

```{r}
dataset |> 
#    left_join(empresas, by = "TICKER") |> 
    mutate(`PREÇO R$` = PRECO) |>
    mutate(DPA = (DY/100) * `PREÇO R$`) |> 
    mutate(`VALUATION BAZIN RS` = DPA / 0.06) |> 
    mutate(`DESCONTO BAZIN %` = 
             ((`PREÇO R$` - `VALUATION BAZIN RS`) / `VALUATION BAZIN RS`) * 100 * -1) |> 
    mutate(`VALUATION GRAHAM R$` = 
             (22.5 * LPA * VPA)^0.5) |> 
    mutate(`DESCONTO GRAHAM %` = 
             ((`PREÇO R$` - `VALUATION GRAHAM R$`) / 
                                  `VALUATION GRAHAM R$`)*100 * -1) |> 
    mutate(`VALUATION GORDON R$` = 
             (DPA * (1 + (`CAGR LUCROS 5 ANOS`/100))) / 1) |> # risco mudei para 1
    mutate(`DESCONTO GORDON %` = 
             ((`PREÇO R$` - `VALUATION GORDON R$`) / 
                                  `VALUATION GORDON R$`)*100 * -1) |> 
    mutate(`CAGR LUCROS 5 ANOS` = 
           if_else(is.na(`CAGR LUCROS 5 ANOS`), 0, `CAGR LUCROS 5 ANOS`)) |>
    mutate(PAYOUT = DPA / LPA) |> 
    mutate(PAYOUT = 
           if_else(is.na(PAYOUT), 0, PAYOUT)) |>
    mutate(`CRESCIMENTO ESPERADO %` = 
             (1 - PAYOUT) * ROE) |> 
    mutate(`MÉDIA DE CRESCIMENTO %` = 
             (`CAGR LUCROS 5 ANOS` + `CRESCIMENTO ESPERADO %`)/2) |> 
    mutate_if(is.double, ~round(., 2)) |> 
    filter(`PREÇO R$` != 0 & `PREÇO R$` < 1000) -> dat
```

```{r}
dat |> 
  filter(!is.na(`DESCONTO GRAHAM %`)) |> 
  filter(!is.na(`LIQUIDEZ MEDIA DIARIA`)) |> 
  filter(`LIQUIDEZ MEDIA DIARIA` > 1000000) |> 
#  arrange(desc(`DESCONTO GRAHAM %`)) 
  mutate(desconto = if_else(VPA > PRECO, "yes", "no")) |> 
  filter(desconto == "yes")
```

3086472-9






